version: "3.3"
services:
  frontend:
    build: 
      context: ./frontend
      args:
        backend: ${backend}
    image: gammu-admin-frontend
    ports:
      - ${frontendPort}:80
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
    depends_on:
      - backend
    
  backend:
    build: 
      context: ./backend
      args:
        login: ${login}
        password: ${password}
    image: gammu-admin-backend
    command: /app/bin/server
    restart: always
    ports:
      - ${backendPort}:8080
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
    volumes:
      - ${gammuPath}:/data
