version: "3.3"
services:
  app:
    build: .
    image: gammu-admin-backend
    container_name: gammu-admin-backend
    command: /app/bin/server
    ports:
      - "8080:8080"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "5m"
    volumes:
      - C:/data/:/data
