name: backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc_test: ^9.1.0
  broadcast_bloc: ^0.1.0-dev.1
  charset: ^1.1.1
  collection: ^1.17.0
  dart_frog: ^0.3.0
  dart_frog_web_socket: ^0.1.0-dev.1
  equatable: ^2.0.5
  path: ^1.8.3

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0